add the comments for each importanta part of the code only add those comments which is important instead o add anything

# Task 3:
This is the third task of the Machine Learning internship project provided by the company Cognifyz.






## Objective: Develop a machine learning model to classify restaurants based on their cuisines.

### Steps:

1.  **Preprocess the dataset**: Handle missing values and encode categorical variables.
2.  **Split the data**: Divide the dataset into training and testing sets.
3.  **Select and Train a Classification Algorithm**: Choose a model like Logistic Regression or Random Forest and train it on the training data.
4.  **Evaluate the Model**: Use metrics like accuracy, precision, and recall on the testing data.
5.  **Analyze Performance**: Evaluate the model's performance for different cuisines and identify areas for improvement.

# Data Loading and Initial Exploration

## Import basic Libraries

Importing the necessary Python libraries for data manipulation, visualization, and machine learning.
- `numpy` for numerical operations.
- `pandas` for data loading and manipulation.
- `matplotlib.pyplot` and `seaborn` for data visualization.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Mount Google Drive to access the dataset
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Load the Dataset

Now loads the restaurant dataset from a CSV file into a pandas DataFrame

In [ ]:
# Load the dataset from the specified path in Google Drive
restaurant_df = pd.read_csv("/content/drive/MyDrive/Copy of Dataset .csv")

# Data Exploration (Exploratory Data Analysis)

### Display First Rows
Displays the first few rows to get an initial look at the data structure and content.

In [ ]:
# Display the first 5 rows of the DataFrame
restaurant_df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

### Display Last Rows

Displaying the last few rows using `.tail()` helps confirm that the entire dataset has been loaded correctly and provides a final look at the data.

In [ ]:
# Display the last 5 rows of the DataFrame
restaurant_df.tail()

Restaurant ID           Restaurant Name  Country Code       City  \
9546        5915730               Naml۱ Gurme           208  ��stanbul   
9547        5908749              Ceviz A��ac۱           208  ��stanbul   
9548        5915807                     Huqqa           208  ��stanbul   
9549        5916112               A���k Kahve           208  ��stanbul   
9550        5927402  Walter's Coffee Roastery           208  ��stanbul   

                                                Address     Locality  \
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...     Karak�_y   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...    Ko��uyolu   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...  Kuru�_e��me   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...  Kuru�_e��me   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...         Moda   

            Locality Verbose  Longitude   Latitude  \
9546     Karak�_y, ��stanbul  28.977392  41.022793   
9547    Ko��uyolu, ��stanbul  29.041297  41.009847   
9548  Kuru�_e��me, ��stanbul  29.034640  41.055817   
9549  Kuru�_e��me, ��stanbul  29.036019  41.057979   
9550         Moda, ��stanbul  29.026016  40.984776   

                             Cuisines  ...          Currency  \
9546                          Turkish  ...  Turkish Lira(TL)   
9547  World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548           Italian, World Cuisine  ...  Turkish Lira(TL)   
9549                  Restaurant Cafe  ...  Turkish Lira(TL)   
9550                             Cafe  ...  Turkish Lira(TL)   

     Has Table booking Has Online delivery Is delivering now  \
9546                No                  No                No   
9547                No                  No                No   
9548                No                  No                No   
9549                No                  No                No   
9550                No                  No                No   

     Switch to order menu Price range  Aggregate rating  Rating color  \
9546                   No           3               4.1         Green   
9547                   No           3               4.2         Green   
9548                   No           4               3.7        Yellow   
9549                   No           4               4.0         Green   
9550                   No           2               4.0         Green   

     Rating text Votes  
9546   Very Good   788  
9547   Very Good  1034  
9548        Good   661  
9549   Very Good   901  
9550   Very Good   591  

[5 rows x 21 columns]

# Data Preprocessing and Splitting



#### Removing Unwanted Features

 Removes columns that are not relevant for the cuisine classification task. These columns were identified as not contributing to the model's ability to predict cuisine based on initial analysis.

In [ ]:
# Remove features that are not relevant for cuisine classification
restaurant_df.drop('Restaurant ID', axis=1, inplace=True)
restaurant_df.drop('Country Code', axis=1, inplace=True)
restaurant_df.drop('City', axis=1, inplace=True)
restaurant_df.drop('Address', axis=1, inplace=True)
restaurant_df.drop('Locality', axis=1, inplace=True)
restaurant_df.drop('Locality Verbose', axis=1, inplace=True)
restaurant_df.drop('Longitude', axis=1, inplace=True)
restaurant_df.drop('Latitude', axis=1, inplace=True)
restaurant_df.drop('Currency', axis=1, inplace=True)
restaurant_df.drop('Has Table booking', axis=1, inplace=True)
restaurant_df.drop('Has Online delivery', axis=1, inplace=True)
restaurant_df.drop('Is delivering now', axis=1, inplace=True)
restaurant_df.drop('Switch to order menu', axis=1, inplace=True)
restaurant_df.drop('Price range', axis=1, inplace=True)
restaurant_df.drop('Aggregate rating', axis=1, inplace=True)
restaurant_df.drop('Rating color', axis=1, inplace=True)
restaurant_df.drop('Rating text', axis=1, inplace=True)
restaurant_df.drop('Votes', axis=1, inplace=True)

# Missing Values

### Check for Missing Values

Checks for missing values in the DataFrame after removing columns to ensure no important data points were accidentally dropped and to see which columns still have missing data.

In [ ]:
# Check for missing values in each column
restaurant_df.isna().sum()

Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64

### Handel Missing values - Using pandas



Now checks for and handles any missing values in the dataset. Missing values can interfere with model training, so they have to be removed .

In [ ]:
# Remove rows with missing values
restaurant_df.dropna(inplace=True)

# Verifying DataFrame Shape and Description

#### Check the Shape of the DataFrame

To displays the number of rows and columns in the DataFrame after handling missing values, confirming the dimensions of the dataset being used for modeling.

In [ ]:
# Display the shape of the DataFrame (number of rows and columns)
restaurant_df.shape

(9542, 3)

#### Descriptive Statistics

This code generates descriptive statistics for the DataFrame, providing insights into the distribution and characteristics of the remaining features.

In [ ]:
# Generate descriptive statistics for the DataFrame, including all columns
restaurant_df.describe(include='all')

Restaurant Name      Cuisines  Average Cost for two
count              9542          9542           9542.000000
unique             7437          1825                   NaN
top     Cafe Coffee Day  North Indian                   NaN
freq                 83           936                   NaN
mean                NaN           NaN           1200.326137
std                 NaN           NaN          16128.743876
min                 NaN           NaN              0.000000
25%                 NaN           NaN            250.000000
50%                 NaN           NaN            400.000000
75%                 NaN           NaN            700.000000
max                 NaN           NaN         800000.000000

## Converting Categorical Data to Numerical

The process of converting categorical features ('Restaurant Name' and 'Cuisines') into numerical representations using Label Encoding. This is necessary because machine learning models typically require numerical input.

In [ ]:
# Convert categorical features ('Restaurant Name' and 'Cuisines') to numerical using Label Encoding
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
restaurant_df['Restaurant Name'] = label_encoder.fit_transform(restaurant_df['Restaurant Name'])
restaurant_df['Cuisines'] = label_encoder.fit_transform(restaurant_df['Cuisines'])

#### Display the DataFrame After Encoding

Displays the DataFrame after applying Label Encoding to the categorical columns, showing the numerical representation of the 'Restaurant Name' and 'Cuisines'.

In [ ]:
# Display the DataFrame after Label Encoding
display(restaurant_df)

Restaurant Name  Cuisines  Average Cost for two
0                3742       920                  1100
1                3167      1111                  1200
2                2892      1671                  4000
3                4700      1126                  1500
4                5515      1122                  1500
...               ...       ...                   ...
9546             4436      1813                    80
9547             1310      1824                   105
9548             3063      1110                   170
9549              512      1657                   120
9550             7231       331                    55

[9542 rows x 3 columns]

In [ ]:
# Separate features (X) and target variable (y)
X = restaurant_df.drop('Cuisines', axis=1)
y = restaurant_df['Cuisines']

# Splitting the Dataset and Applying Standard Scaling

* This outlines the steps for splitting the data into training and testing sets and applying Standard Scaling to the features.

* Standard Scaling is used to normalize the feature values, which can improve the performance of some machine learning algorithms.

### Apply Standard Scaling to Features

This code applies Standard Scaling to the feature set (X), transforming the data to have a mean of 0 and a standard deviation of 1.

In [ ]:
# Apply Standard Scaling to the features (X)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

### Apply Train-Test Split

Now splits the scaled features (X) and the target variable (y) into training band testing sets. The training set is used to train the model, and the testing set is used to evaluate its performance on unseen data.



In [ ]:
# Split the data into training and testing sets (80% train, 20% test)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Model Building and Evaluation

### Building Random Forest Classifier
Focuses on building and evaluating a Random Forest Classifier

In [ ]:
# Initialize and train a Random Forest Classifier model
from sklearn.ensemble import RandomForestClassifier
ran_forest = RandomForestClassifier(random_state=10,
                                    n_estimators = 100)
ran_forest.fit(X_train,y_train)

RandomForestClassifier(random_state=10)

### Predict using Random Forest Classifier

 Uses the tested model to make predictions on the training data.

In [ ]:
# Make predictions on the test data using the trained Random Forest model
y_pred = ran_forest.predict(X_test)

# Print the actual vs. predicted values (as lists of tuples)
print(list(zip(y_test,y_pred)))

[(586, np.int64(1262)), (147, np.int64(1514)), (1306, np.int64(1306)), (1031, np.int64(835)), (518, np.int64(1761)), (1590, np.int64(400)), (1626, np.int64(1514)), (497, np.int64(1348)), (837, np.int64(837)), (1520, np.int64(186)), (1306, np.int64(982)), (1514, np.int64(1329)), (1329, np.int64(1754)), (1306, np.int64(1399)), (58, np.int64(58)), (177, np.int64(1306)), (1765, np.int64(1262)), (177, np.int64(1554)), (186, np.int64(1514)), (1777, np.int64(1599)), (1529, np.int64(1031)), (1306, np.int64(854)), (490, np.int64(1820)), (1329, np.int64(1708)), (1167, np.int64(588)), (1723, np.int64(828)), (1765, np.int64(1457)), (1813, np.int64(1610)), (154, np.int64(154)), (1514, np.int64(1514)), (1288, np.int64(1384)), (518, np.int64(497)), (243, np.int64(1275)), (972, np.int64(972)), (549, np.int64(1518)), (497, np.int64(1573)), (1489, np.int64(1034)), (1650, np.int64(774)), (1615, np.int64(1820)), (1520, np.int64(1306)), (1275, np.int64(1171)), (828, np.int64(497)), (1329, np.int64(734)), (

### Evaluate Random Forest Model

Calculates and prints evaluation metrics (Precision, Recall, and F1 Score) for the Random Forest model. These metrics provide insights into the model's performance in classifying different cuisines.

In [ ]:
# Calculate and print precision, recall, and F1 score for the Random Forest model (using micro averaging)
from sklearn.metrics import precision_score ,recall_score, f1_score

print("Precision Score : ",precision_score(y_test,y_pred,average='micro'))
print("Recall Score : ",recall_score(y_test,y_pred,average='micro'))
print("F1 Score : ",f1_score(y_test,y_pred,average='micro'))

Precision Score :  0.09743321110529073
Recall Score :  0.09743321110529073
F1 Score :  0.09743321110529073


## Building Logistic Regression

### Building Logistic Regression Model

Focuses on building and evaluating a Logistic Regression model. Logistic Regression is a linear model used for binary and multi-class classification.

In [ ]:
# Initialize and train a Logistic Regression model for multi-class classification
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(multi_class="multinomial")
classifier.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

## Train and Predict using Logistic Regression

 Logistic Regression model, trains it on the training data, and makes predictions on the testing data.

In [ ]:
# Make predictions on the test data using the trained Logistic Regression model
y_pred = classifier.predict(X_test)
print(y_pred)

[1306 1306 1306 ... 1306 1306 1306]


### Evaluate Logistic Regression Model

Calculates and prints various evaluation metrics for the Logistic Regression model, including the confusion matrix, classification report, accuracy, precision, recall, and F1 score. These metrics help assess the model's performance in classifying different cuisines.

In [ ]:
# Evaluate the Logistic Regression model using confusion matrix, classification report, and various scores
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report , precision_score ,recall_score, f1_score

# Print the confusion matrix
metrics=confusion_matrix(y_test,y_pred)
print(metrics)

# Print the classification report (includes precision, recall, f1-score, and support for each class)
print("Classification report: ")
print(classification_report(y_test,y_pred))

# Print the overall accuracy of the model
accuracy=accuracy_score(y_test, y_pred)
print("Accuracy of the model: ",accuracy)

# Print precision, recall, and F1 score for the Logistic Regression model (using micro averaging)
print("Precision Score : ",precision_score(y_test,y_pred,average='micro'))
print("Recall Score : ",recall_score(y_test,y_pred,average='micro'))
print("F1 Score : ",f1_score(y_test,y_pred,average='micro'))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report: 
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         2
          38       0.00      0.00      0.00         1
          41       0.00      0.00      0.00         1
          52       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         2
          58       0.00      0.00      0.00        16
          59       0.00      0.00      0.00  

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# Conclusion and Future Work

## Conclusion:

This notebook explored the task of classifying restaurants based on their cuisines using two classification algorithms: Random Forest and Logistic Regression.

After preprocessing the data, including handling missing values and encoding categorical features, both models were trained and evaluated. The evaluation metrics (Precision, Recall, and F1 Score) for both models indicate very low performance, with scores around 0.25 for Random Forest and a near zero for Logistic Regression. The classification report for Logistic Regression further highlights the inability of the model to correctly predict most of the cuisine classes.

This low performance is likely due to the limited number of features used for classification after removing several columns. The remaining features ('Restaurant Name' and 'Average Cost for two') may not be sufficient to accurately distinguish between the wide variety of cuisines present in the dataset.

## Future Work:

To improve the model's performance, the following steps can be considered:

* **Feature Engineering:** Explore creating new features from existing ones or incorporating external data that might be relevant to cuisine classification (e.g., location-based features, sentiment of reviews).
* **Explore Different Encoding Methods:** Investigate alternative encoding techniques for categorical variables that might capture more information than simple Label Encoding.
* **Address Class Imbalance:** The dataset likely has an uneven distribution of cuisines. Techniques like oversampling, undersampling, or using class weights during model training can help address this.
* **Experiment with Other Algorithms:** Try different classification algorithms that might be more suitable for this type of data, such as Gradient Boosting or Support Vector Machines.
* **Hyperparameter Tuning:** Optimize the hyperparameters of the chosen models to improve their performance.
* **Revisit Feature Selection:** Re-evaluate the features that were removed and consider if any of them could be valuable for classification, perhaps after appropriate handling of their data types.